version: '3.8'
services:
  frontend:
    image: mrbilalshafiq:frontend
    build: ./1-frontend
    ports:
    - "5000:5000"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      SECRET_KEU: YOUR_KEY
  chargen:
    image: mrbilalshafiq:chargen
    build: ./2-chargen
  numgen:
    image: mrbilalshafiq:numgen
    build: ./3-numgen
  prizegen:
    image: mrbilalshafiq:prizegen
    build: ./4-prizegen
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  db:
    build: ./db
    image: mrbilalshafiq/db:latest
    ports:
    - target: 3306
      published: 3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - myvolume:/var/lib/mysql
volumes: 
  myvolume:
